version: '3'
services:
  vue-app:
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Füge eine benutzerdefinierte Nginx-Konfigurationsdatei hinzu
    ports:
      - "9876:80"
